<wsdl:definitions name="AccountServices" targetNamespace="http://b2b.tracfone.com/AccountServices" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://b2b.tracfone.com/AccountServices" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsd1="http://b2b.tracfone.com/AccountServices">
  <wsdl:types>
    <xsd:schema>
    	<xsd:import namespace="http://b2b.tracfone.com/AccountServices" schemaLocation="../xsd/AccountServices.xsd"/>
    </xsd:schema>
  </wsdl:types>

  <wsdl:message name="updateAccountRequest">
  	<wsdl:part name="parameters" element="tns:updateAccountRequest"/>
  </wsdl:message>
  <wsdl:message name="updateAccountResponse">
  	<wsdl:part name="parameters" element="tns:updateAccountResponse"/>
  </wsdl:message>
  <wsdl:portType name="AccountUpdateOS">


    
    

    <wsdl:operation name="updateAccount">
    	<wsdl:input message="tns:updateAccountRequest"/>
    	<wsdl:output message="tns:updateAccountResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="AccountServicesSOAP" type="tns:AccountUpdateOS">

  	<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  	<wsdl:operation name="updateAccount">

  		<soap:operation soapAction="http://www.tracfone.com/AccountDataServices/updateAccount"/>
  		<wsdl:input>

  			<soap:body use="literal"/>
  		</wsdl:input>
  		<wsdl:output>

  			<soap:body use="literal"/>
  		</wsdl:output>
  	</wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="AccountUpdateOS">
    <wsdl:port binding="tns:AccountServicesSOAP" name="AccountServicesSOAP">
      <soap:address location="https://www.tracfone.com/DataServices/AccountServices"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>