<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:tns="http://www.tracfone.com/AccountSpringFarmServices"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns0="http://b2b.tracfone.com/AccountServices"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:common="http://www.tracfone.com/CommonTypes"
                xmlns:pref2="http://www.tracfone.com/OrganizationCommonTypes"
                xmlns:phone="http://www.tracfone.com/PhoneCommonTypes"
                xmlns:acct="http://www.tracfone.com/AccountCommonTypes"
                xmlns:pay="http://www.tracfone.com/PaymentCommonTypes"
                xmlns:pref1="http://www.tracfone.com/RuntimeFault"
                xmlns:ns1="http://www.tracfone.com/CarrierCommonTypes"
                xmlns:pref="http://www.tracfone.com/SecurityCommonTypes"
                xmlns:plan="http://www.tracfone.com/ServicePlanCommonTypes">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../xsd/AccountServices.xsd"/>
        <oracle-xsl-mapper:rootElement name="forgotPasswordRequest"
                                       namespace="http://b2b.tracfone.com/AccountServices"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../SpringFarmServices/xsd/AccountSpringFarmServices.xsd"/>
        <oracle-xsl-mapper:rootElement name="getCustomerProfileRequest"
                                       namespace="http://www.tracfone.com/AccountSpringFarmServices"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE FEB 06 14:54:44 EST 2018].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:getCustomerProfileRequest>
      <common:requestToken>
        <common:clientTransactionId>
          <xsl:value-of select="/ns0:forgotPasswordRequest/common:requestToken/common:clientTransactionId"/>
        </common:clientTransactionId>
        <common:clientId>
          <xsl:value-of select="/ns0:forgotPasswordRequest/common:requestToken/common:clientId"/>
        </common:clientId>
      </common:requestToken>
      <common:brandName>
        <xsl:value-of select="/ns0:forgotPasswordRequest/common:brandName"/>
      </common:brandName>
      <common:sourceSystem>
        <xsl:value-of select="/ns0:forgotPasswordRequest/common:sourceSystem"/>
      </common:sourceSystem>
      <common:language>
        <xsl:value-of select="/ns0:forgotPasswordRequest/common:language"/>
      </common:language>
      <tns:accountId>
        <acct:accountIdentifierName>MIN</acct:accountIdentifierName>
        <acct:accountIdentifierValue>
          <xsl:value-of select="/ns0:forgotPasswordRequest/ns0:min"/>
        </acct:accountIdentifierValue>
      </tns:accountId>
    </tns:getCustomerProfileRequest>
  </xsl:template>
</xsl:stylesheet>
